### ISSUE TITLE
Audio "clipping" / "truncating" not working

### ISSUE THREAD

**Issue by max-winderbaum** [iq-eq-us/voicebox#4]
From the [TikTok](https://www.tiktok.com/@rileyandrichy/video/7213826187334798634?_r=1&_t=8atPRzbYZuo) at around 40 seconds you can see Riley typing very quickly and VoiceBox keeping up - I'm only hearing full words that get very backed up over time if I type quickly

I'm not sure how else to explain this so let me know if I can provide more of a repro

**Comment by Raymo111** [comment]
Riley was using a beta version in the video with the smooth read option enabled (right now it doesn't do anything). I'm pushing an update that enables that soon!
